permalink: /:year:month:day/:title
url:  https://jcmundy.github.io/
baseurl: /project

# variables
name: Digital Scholarship Blog
description: This blog discusses digital scholarship.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
